services:
  postgres:
    image: postgres:16-alpine
    container_name: noker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: noker
      POSTGRES_PASSWORD: noker
      POSTGRES_DB: noker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d

  noker:
    build: .
    image: noker:latest 
    container_name: noker-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
    - .env
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data: